import { z } from "zod";

/**
 * Two different kinds of identifier exist in this product:
 *
 * - Application IDs (pages, sections, elements, fields) are UUIDs generated by whoever creates the
 *   node. They live inside the builder document and must stay stable across renames.
 * - Resource IDs (projects, media, posts, workspaces) are MongoDB ObjectIds exposed to the API as
 *   24-character hex strings. The database layer maps between the two representations.
 */

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const OBJECT_ID = /^[0-9a-f]{24}$/i;

const webCrypto = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;

/** Creates a new application ID. Throws rather than falling back to a weak random source. */
export function createId(): string {
  if (!webCrypto?.randomUUID) {
    throw new Error("Web Crypto randomUUID is unavailable in this runtime");
  }
  return webCrypto.randomUUID();
}

export function isApplicationId(value: unknown): value is string {
  return typeof value === "string" && UUID.test(value);
}

export function isResourceId(value: unknown): value is string {
  return typeof value === "string" && OBJECT_ID.test(value);
}

export const applicationIdSchema = z.string().regex(UUID, "must be a UUID");
export const resourceIdSchema = z.string().regex(OBJECT_ID, "must be a 24-character hexadecimal id");
